name: Build with CUDA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Jimver/cuda-toolkit@v0.2.22
      id: cuda-toolkit
      with:
        cuda: '12.5.0'

    - run: echo "Installed cuda version is ${{steps.cuda-toolkit.outputs.cuda}}"
    
    - run: echo "Cuda install location ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
    
    - run: nvcc -V
  
    - name: create output
      run: mkdir output
  
    - name: make build CUDA
      run: make graphics-cuda.out
