name: Build with OpenCL

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libboost-program-options-dev \
            ocl-icd-opencl-dev \
            opencl-headers \
            clinfo

      - name: Check OpenCL Installation
        run: |
          clinfo | head -n 20
          ls -l /usr/lib/libOpenCL*

      - name: Checkout LodePNG
        run: git submodule update --init --recursive

      - name: Create Output Directory
        run: mkdir -p output

      - name: Build OpenCL Version
        run: |
          make clean
          make graphics-opencl.out

      - name: Test OpenCL Version
        run: |
          ./graphics-opencl.out --help
