name: Build with OpenCL

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libboost-program-options-dev \
            ocl-icd-opencl-dev \
            opencl-headers \
            clinfo \
            wget \
            gnupg \
            lsb-release

      - name: Install Intel OpenCL Runtime
        run: |
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install -y intel-oneapi-runtime-opencl

      - name: Check OpenCL Installation
        run: |
          clinfo | head -n 20
          ls -l /usr/lib/libOpenCL*
          ls -l /usr/lib/x86_64-linux-gnu/libOpenCL*

      - name: Checkout LodePNG
        run: git submodule update --init --recursive

      - name: Create Output Directory
        run: mkdir -p output

      - name: Build OpenCL Version
        run: |
          make clean
          make graphics-opencl.out

      - name: Test OpenCL Version
        run: |
          ./graphics-opencl.out --help
